# Generated by Django 5.1.1 on 2024-10-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_league_leaguemembership_league_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='country',
            new_name='location',
        ),
    ]
