# Generated by Django 5.1.1 on 2024-11-05 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_league_id_alter_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguemembership',
            name='notes',
        ),
        migrations.AddField(
            model_name='leaguemembership',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='leaguemembership',
            name='still_active',
            field=models.BooleanField(default=True),
        ),
    ]
